Models/MeetingInfo.cs
namespace MeetingApp.Models { 
    public class MeetingInfo {
        public int Id { get;set;}
        public string? Location { get;set;}
        public DateTime Date { get;set;}
        public int NumberOfPeople { get;set;}

    }
}

Models/Repository.cs
namespace MeetingApp.Models {
    public static class Repository {
        private static List <UserInfo> _users = new();

        static Repository() {
            _users.Add(new UserInfo() { Id=1, Name = "Mirza", Email = "abc@gmail.com", Phone = "11111", WillAttend=true});
            _users.Add(new UserInfo() { Id=2, Name = "Bugra", Email = "123@gmail.com", Phone = "22222", WillAttend=true});
            _users.Add(new UserInfo() { Id=3, Name = "Ozcelik", Email = "xyz@gmail.com", Phone = "33333", WillAttend=false});
        }
        public static List<UserInfo> Users  {
            get {
                return _users;
            }
        }

        public static void CreateUser(UserInfo user){
            user.Id = Users.Count + 1;
            _users.Add(user);
        }

        public static UserInfo? GetById(int id) {
            return _users.FirstOrDefault(user => user.Id == id);
        }
    }
}

Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models {
    public class UserInfo {
        public int Id { get; set;}

        [Required]
        public string? Name { get; set; }
       
        [Required]
        public string? Phone { get; set; }

        [Required]
        [EmailAddress]
        public string? Email { get; set; }
        
        [Required]
        public bool? WillAttend { get; set; }
    }
}

Controllers/HomeController.cs
using System.Runtime.CompilerServices;
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers {
    public class HomeController : Controller {
        // localhost
        // localhost/home
        // localhost/home/index
        public IActionResult Index() {
            int clock = DateTime.Now.Hour;
            // ViewBag.salute = clock > 12 ? "Have a nice days" : "Morning";
            // ViewBag.username = "Mirza";

            ViewData["Salute"] = clock > 12 ? "Have a nice days" : "Morning";
            // ViewData["Username"] = "Mirza";
            int UserCount = Repository.Users.Where(info => info.WillAttend == true).Count();


            var meetingInfo = new MeetingInfo() {
                Id = 1,
                Location = "Ankara, Etimesgut",
                Date = new DateTime(2024, 01, 20, 20, 0, 0),
                NumberOfPeople = UserCount
            };
            return View(meetingInfo);
        }
    }
}

Controllers/MeetingController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class MeetingController : Controller
    {     
        [HttpGet]
        public IActionResult Apply() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Apply(UserInfo model) {
            if(ModelState.IsValid){
                Repository.CreateUser(model);
                ViewBag.UserCount = Repository.Users.Where(info => info.WillAttend == true).Count();
                return View("Thanks", model);
            } else{
                return View(model);
            }
        }
        
        [HttpGet]
        public IActionResult List() 
        {
            return View(Repository.Users);
        }
        
        //meeting/details/2
        //application-detail
        public IActionResult Details(int id) {
            return View(Repository.GetById(id));
        }
    }
}

Views/Home/Index.cshtml
@model MeetingInfo
@{
    ViewBag.Title = "Meeting Application";
    Layout = "_Layout2";
}
<main class="text-center">
    <h1 class="h4">@ViewData["Salute"]</h1>
    <p>Please report your meeting attendance status.</p>
    <div class="card my-2">
        <ul class="list-group list-group-flush">
            <li class="list-group item">@Model.Location</li>
            <li class="list-group item">@Model.Date.ToString("dd/MM/yyyy HH:mm:ss") Will Take Place On</li>
            <li class="list-group item">@Model.NumberOfPeople Participants</li>
        </ul>
    </div>
    <a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Make An Application</a>
</main>

Views/Meeting/Apply.cshtml
@model UserInfo
@{
    ViewBag.Title = "Application Form";
}
<h1 class="h4 text-center">Meeting Participation Form</h1>
<form method="post" action="/Meeting/Apply" novalidate>
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Phone</label>
        <input asp-for="Phone" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" class="form-control" >
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">Participation Status</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="">Choose</option>
            <option value="true">Yes, I am coming</option>
            <option value="fale">No, I am busy.</option>
        </select>
    </div>
    <button class="btn btn-primary" type="submit">Save</button>
</form>

Views/Meeting/Details.cshtml
@model UserInfo

@{ 
    ViewBag.Title = "Application Detail";
}

@{
    var className = @Model.WillAttend == true ? "primary" : "danger";
}

<main class="text-center">
    <h1 class="h4">Application Detail</h1>
    <p>
        <span class="badge text-bg-@className">
            @if(Model.WillAttend == true) {
                <text>Attending</text>
            } else{
                <text>Not Attending</text>
            }
        </span>
    </p>
        <p>Name: @Model.Name</p>
        <p>Email: @Model.Email</p>
        <p>Phone: @Model.Phone</p>
        <a asp-controller="Meeting" asp-action="List" class="btn btn-outline-@className">Attendance List</a>
</main>

Views/Meeting/List.cshtml
@model List<UserInfo>
@{
    ViewBag.Title = "Meeting Attendance List";
}
<main class="text-center">

    <h1 class="h4">Meeting Attendance List</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Name</td>
                <td>Email</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @{ int i = 0;  }

            @foreach(var user in Model) {
                var situation = user.WillAttend == true ? "Yes" : "No"; 
                var className = user.WillAttend == true ? "table-success" : "table-danger";

                if(user.WillAttend == true) {
                    i++;
                }
                <tr class="@className">
                    <td>@user.Name</td>
                    <td>@situation</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detail</a>
                    </td>
                    <td></td>
                </tr>
            }
            
        </tbody>
    </table>
    <div class="card">
        <div class="card-body">
            <span>Participant Count: @i</span>
        </div>
    </div>
</main>

Views/Meeting/Thanks.cshtml
@model UserInfo
@{
    ViewBag.Title = "Meeting Summary";
}
<main class="text-center">
<h1 class="h4">Meeting Summary</h1>
    @if(Model.WillAttend == true){
        <p>Thanks, @Model.Name @ViewBag.UserCount people attend the meeting with you.</p>
        <a class="btn btn-sm btn-outline-primary" href="/meeting/list">List Participants</a>
    } else{
        <p>@Model.Name, We are sad because you did not attend.</p>
        <a class="btn btn-sm btn-outline-primary" href="/meeting/apply">Application Form</a>
    }
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-primary text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="card">
                    <div class="card-body"></div>
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-danger text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card">
                    <div class="card-body"></div>
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</body>
</html>